import { 
  Loader2,
  CheckCircle2,
  AlertCircle,
  Briefcase,
  Plus,
  Edit2,
  Trash2,
  Eye,
  EyeOff,
  Menu,
  X,
  LogOut,
  Settings,
  BarChart3,
  ListTodo,
  Users,
  FileText,
  MessageSquare,
  Upload,
  Download,
  Filter,
  Search,
  Calendar,
  Clock,
  AlertTriangle,
  Checkmark,
  Flame,
} from 'lucide-react'

export const Icons = {
  spinner: Loader2,
  check: CheckCircle2,
  alert: AlertCircle,
  logo: Briefcase,
  plus: Plus,
  edit: Edit2,
  delete: Trash2,
  eye: Eye,
  eyeOff: EyeOff,
  menu: Menu,
  close: X,
  logout: LogOut,
  settings: Settings,
  analytics: BarChart3,
  tasks: ListTodo,
  users: Users,
  file: FileText,
  comment: MessageSquare,
  upload: Upload,
  download: Download,
  filter: Filter,
  search: Search,
  calendar: Calendar,
  clock: Clock,
  warning: AlertTriangle,
  success: Checkmark,
  fire: Flame,
}
